---
- name: Download and move html file to correct folder
  ansible.builtin.get_url:
        url: "{{ site_1 }}"
        dest: "{{ dest_path }}"

- name: Restart httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted
